name: Build and Release

on:
  push:
    tags:
      - 'v*' # 匹配以v开头的tag，例如v1.0.0

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'server/go.mod'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install build toolchain
        run: |
          sudo apt install -y make gcc mingw-w64

      - name: Build
        run: |
          make init
          make build

      # https://github.com/actions/upload-artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: server/bin/*

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      # https://github.com/actions/download-artifact
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          token: ${{ secrets.GHP_TOKEN }}
          tag_name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            *